---
name: image-builder

on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build operator docker image
      run: make docker-build

  bundle-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build operator bundle docker image
      run: make bundle-build

  catalog-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18", "1.19"]
    if: github.repository == 'red-hat-storage/odf-operator'
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: docker/login-action@v2
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_ROBOT_TOKEN }}

    - name: Build catalog docker image
      env:
        IMAGE_TAG: ${{ github.run_id }}
      run: |
        make bundle-build bundle-push catalog-build
