---
name: golangci-lint

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.45.2
          args: -E gosec --timeout=6m
