---
name: golangci-lint

on:
  push:
    branches: ['main', 'release-*']
  pull_request:
    branches: ['*']

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.53.1
        args: -E gosec --timeout=6m
